- name: install and run nginx
  hosts: localhost
  become: yes
  tags:
  - postfix
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: started

  - name: install postfix
    ansible.builtin.package:
     name: postfix
     state: present
  - name: run postfix
    ansible.builtin.service:
     name: postfix
     state: started
  