- name: variables declaration
  hosts: localhost
  become: yes
  loop:
  - git
  - mysql
  - postfix
  tasks:
  -name: install packages
   ansible.builtin.package:
    name: "{{item}}"
    state: present
          