- name: variables declaration
  hosts: localhost
  vars:
   name: sudha
   age: 24
  vars_files:
  - varis.yaml
  tasks: 
  - name: variables declaration
    vars:
     name: jyothi
    ansible.builtin.debug:
     msg: "{{name}}, {{age}}, {{profession}}"
          