- name: variables declaration
  hosts: localhost
  vars:
   name: sudha
   age: 24
  vars_prompt:
   name: enter your username
   password: enter your password
   private: false
  tasks: 
  - name: variables declaration
    ansible.builtin.debug:
     msg: "{{name}}, {{password}}"
          