- name: variables declaration
  hosts: localhost
  become: yes
  
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{name.item}}"
     state: "{{state.item}}"

    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'present'}
    - {name: 'postfix', state: 'present'}