- name: variables declaration
  hosts: localhost
  vars: 
   skills: 
    - devops
    - mysql
   experience:
    devops: 1
    mysql: 2
  tasks: 
  - name: variables declaration
    ansible.builtin.debug:
     msg: "{{skills}}", {{experience}}"
          